### ISSUE TITLE
Content security policy issue

### ISSUE THREAD

**Issue by homanp** [pusher/pusher-realtime-producthunt-extension#1]
Hey guys,

Tried installing your extension and it throws an error because Pusher is trying to load a http:// script. Thus the realtime does not really work. 

Anyway to fix this?

Great work btw!

**Comment by leggetter** [comment]
@homanp I've got a fix in #2. I'm looking at getting that updated on the Chrome Store. I'll update when it has been updated in the store.

Thanks for reporting!
